BlogBlogBundle_homepage:
    path:  /
    defaults: { _controller: BlogBlogBundle:Page:index }
    requirements:
      methods:  GET
BlogBlogBundle_contact:
    path:  /contact
    defaults: { _controller: BlogBlogBundle:Page:contact }
    requirements:
      methods:  GET
BlogBlogBundle_blog_show:
    path:  /{id}
    defaults: { _controller: BlogBlogBundle:Blog:show }
    requirements:
        methods:  GET
        id: \d+
BlogBlogBundle_about:
    path:  /about
    defaults: { _controller: BlogBlogBundle:Page:about }
    requirements:
        methods:  GET