BlogBlogBundle_homepage:
    path:  /
    defaults: { _controller: BlogBlogBundle:Page:index }
    requirements:
      methods:  GET
BlogBlogBundle_contact:
    path:  /contact
    defaults: { _controller: BlogBlogBundle:Page:contact }
    requirements:
      methods:  GET